#!/bin/bash

#DEBHELPER#

# postrm script for cryptsetup-modified-functions

#set -e

case "$1" in
  purge|remove) dpkg-divert --quiet                                               \
                            --remove                                              \
                            --package cryptsetup-modified-functions               \
                            --rename                                              \
                            --divert /lib/cryptsetup/cryptdisks.functions.distrib \
                            /lib/cryptsetup/cryptdisks.functions
                ;;

             *) :
                ;;
esac 

exit 0
