#!/bin/bash

#DEBHELPER#

# preinst script for cryptsetup-modified-functions

#set -e

case "$1" in
  install|upgrade) dpkg-divert --quiet                                               \
                               --add                                                 \
                               --package cryptsetup-modified-functions               \
                               --rename                                              \
                               --divert /lib/cryptsetup/cryptdisks-functions.distrib \
                               /lib/cryptsetup/cryptdisks-functions
                   ;;

                *) :
                   ;;
esac 

exit 0
